packer {
  required_plugins {
    lightsail = {
      version = ">= 0.0.2"
      source  = "github.com/wdahlenburg/lightsail"
    }
  }
}

source "lightsail" "autogenerated_1" {
  access_key = "{{ user `LIGHTSAIL_ACCESS_KEY` }}"
  secret_key= "{{ user `LIGHTSAIL_SECRET_KEY` }}"
  region = "us-east-1a"
  snapshot_name = "test_snapshot"
  bundle_id = "nano_2.0"
  blueprint_id = "test_snapshot"
  timeout = "15m"
}

build {
  sources = ["source.lightsail.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "apt-get update",
      "apt-get upgrade -y",
      "echo '<ssh-key>' | tee /root/.ssh/authorized_keys"
    ]
  }
}
