packer {
  required_plugins {
    lightsail = {
      version = ">= 0.0.4"
      source  = "github.com/wdahlenburg/lightsail"
    }
  }
}

source "lightsail-lightsail" "autogenerated_1" {
  access_key = var.access_key
  secret_key= var.secret_key
  regions = var.regions
  snapshot_name = "test_snapshot"
  bundle_id = var.bundle_id
  blueprint_id = var.blueprint_id
  timeout = "15m"
}

build {
  sources = ["source.lightsail-lightsail.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "sudo apt-get update",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq",
      "echo '<ssh-key>' | sudo tee /root/.ssh/authorized_keys"
    ]
  }
}
